ita-social-projects/StreetCode_Client

src/app/common/hooks/external/useMediaQuery.hook.ts, src/assets/sass/_utils.functions.scss, src/assets/sass/mixins/_media.mixins.scss, src/assets/sass/mixins/_vendor.mixins.scss
=> Fixed two major bugs related to media query mixin and hook.

src/features/RelatedFiguresBlock/RelatedFigures.component.tsx, src/features/RelatedFiguresBlock/RelatedFigures.styles.scss
=> fix block representation for less then 4 elements

src/app/common/hooks/scrolling/useScrollDirection.hook.ts, src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.d.ts, src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.hook.ts, src/app/common/hooks/scrolling/useScrollPosition/useScrollPosition.utils.ts, src/components/StreetcodeComponent/Streetcode.component.tsx, src/components/StreetcodeComponent/Streetcode.styles.scss, src/index.scss
=> Added scroll-state observing hooks and adjusted global overflow styling.

src/features/MainBlock/MainBlock.component.tsx, src/features/MainBlock/MainBlock.styles.scss
=> fixed background and added hovers

src/app/layout/footer/Footer.component.tsx, src/app/layout/footer/Footer.styles.scss, src/features/TextBlock/ReadMore/ReadMore.component.tsx, src/features/TextBlock/ReadMore/ReadMore.styles.scss
=> fixed text and added hovers for footer

src/app/api/additional-content/subtitles.api.ts, src/app/stores/subtitles-store.ts, src/features/StreetcodePage/TickerBlock/Ticker.component.tsx, src/models/additional-content/subtitles.model.ts
=> Ticker api sync

src/app/api/media/audios.api.ts, src/app/common/components/AudioPlayer/AudioPlayer.component.tsx, src/app/common/constants/api-routes.constants.ts, src/app/stores/audio-store.ts, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> added audio back-end connection

package-lock.json, package.json, src/features/ProgressBar/ProgressBar.component.tsx, src/features/ProgressBar/ProgressBar.styles.scss, src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx, src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss, src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.component.tsx, src/features/StreetcodePage/MapBlock/Map/Map.component.tsx
Merge next fixes:
1) Margin between components and contents
2) Progress bar fixes
3) Map scrolling
=> MapScrollingAndWidth

src/app/common/components/AudioPlayer/AudioPlayer.component.tsx, src/app/common/components/AudioPlayer/AudioPlayer.styles.scss, src/app/stores/timeline-store.ts, src/features/SlickSlider/SlickSlider.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx, src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.component.tsx, src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.styles.scss
=> Update streetcode card and timeline

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
new design & adaptivity
dev
ToDo
ToDo
ToDo
=> header-fixes

src/app/common/components/modals/Sources/SourcesModal.styles.scss
=> scrollbar fixing

src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss, src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx, src/features/SlickSlider/SlickSlider.component.tsx, src/features/SlickSlider/index.ts, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
In Art I had to replace a color of arrows in a lightbox
In Wow-facts I needed to: 
* Fix "jumping" in animation 
* Change pagination for "A little more" button
In Art I added filters for arrows
In Wow-facts :
* For animation added new logic based on "edges" and also added something like "wait for animation" for preventing overclicking
* Decreased pagination for the heading of slide text and then for "A little more" button
=> Added required fixes in Art and Wow-Fact components 

src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
I had to:
* Change the number of words from 300 to 250 in the main text
* Animation while overclicking
(In addition, pagination also was changed)
Animation:  I added extra time for actioning
=> Fixes in Wow-Fact component

src/app/api/streetcode/related-figure.api.ts, src/app/api/streetcode/streetcodes.api.ts, src/app/common/components/TagList/TagList.component.tsx, src/app/common/components/modals/Tags/TagsListModal/TagsListModal.component.tsx, src/app/common/components/modals/Tags/TagsListModal/TagsListModal.styles.scss, src/app/common/components/modals/Tags/TagsModal.component.tsx, src/app/common/components/modals/Tags/TagsModal.styles.scss, src/app/common/constants/api-routes.constants.ts, src/app/layout/ModalWrapper.component.tsx, src/app/stores/modal-store.ts, src/app/stores/related-figures-store.ts, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
modal for tag dev in relative figures
dev
ToDo
ToDo
ToDo
=> Upload progress

src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.component.tsx, src/app/common/components/modals/Tags/TagsModal.component.tsx, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss, src/app/stores/related-figures-store.ts, src/features/StreetcodePage/MainBlock/MainBlock.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx
Implementation of the tags hook for the communication with related figures block and bug fixing.
dev
ToDo
ToDo
ToDo
=> History relations tags modal fixes

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss, src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.styles.scss
=> header drawer fix

package-lock.json, package.json, src/features/AdminPage/AdminPage.component.tsx, src/features/AdminPage/AdminPage.styles.scss, src/features/AdminPage/PageBar/PageBar.component.tsx, src/features/AdminPage/PageBar/PageBar.styles.scss, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx, src/features/AdminPage/StreetcodesTable/StreetcodesTable.styles.scss, src/models/streetcode/streetcode-types.model.ts
Routing:
Added route for admin main page.
Components:
Added admin main page component as wrap for whole page.
Inside admin page logic of showing all streetcodes implemented and designed.
This pull request is a MVP of admin main page and it will be changed with time.
=> StreetcodeTable-admin-panel-main

src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx
=> fix timeline (good centering slides) 

src/features/StreetcodePage/MapBlock/Statistics/Statistics.component.tsx, src/features/StreetcodePage/MapBlock/Statistics/Statistics.styles.scss
=> toponym changes

src/features/AdminPage/NewStreetcode/HistoryRelations/components/InputPanel.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/models/streetcode/related-figure.model.ts, src/models/streetcode/streetcode-types.model.ts
=> added some model changes

src/app/common/components/modals/RelatedFigures/RelatedFiguresModal.styles.scss, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss, src/models/streetcode/related-figure.model.ts
=> Updated "Read more" modal

src/app/api/streetcode/streetcodes.api.ts, src/features/AdminPage/AdminPage.styles.scss, src/features/AdminPage/StreetcodesTable/FormatDateAlgorithm.tsx, src/features/AdminPage/StreetcodesTable/SearchMenu.component.tsx, src/features/AdminPage/StreetcodesTable/SearchMenu.styles.scss, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx, src/features/AdminPage/StreetcodesTable/StreetcodesTable.styles.scss, src/models/streetcode/getAllStreetcodes.request.ts
=> Admin-panel-streetcodes-table

src/features/ProgressBar/ProgressBar.styles.scss, src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.styles.scss, src/features/StreetcodePage/MapBlock/Map/Map.component.tsx, src/features/StreetcodePage/MapBlock/Map/Map.styles.scss, src/features/StreetcodePage/MapBlock/MapBlock.styles.scss, src/features/StreetcodePage/MapBlock/Statistics/Info.styles.scss, src/features/StreetcodePage/MapBlock/Statistics/Statistics.styles.scss
=> map-adapivity

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss, src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.styles.scss, src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
Fixes after PO call on 27th of March.
Affected Header Drawer slider and height of the menu bar.
=> Side menu fixes

src/app/api/streetcode/streetcodes.api.ts, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx, src/models/streetcode/getAllStreetcodes.request.ts, src/models/streetcode/getAllStreetcodes.response.ts
=> GetAllStreetcodes with new response and request

src/app/common/hooks/scrolling/useSticky.hook.ts, src/features/StreetcodePage/Streetcode.component.tsx
IsSticky function needed to be moved before merge.
Created useSticky hook for mentioned purpose.
=> Sticky refactor.

src/app/common/components/Video/Video.styles.scss
=> fixed bug with max-height

src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
dev
Not working link for related figures.
Fixed link for related figures according to the new hook.
=> Hotfix: Url linking for related figures in modal

src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
=> fixed redirection to the start of the page

src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.styles.scss, src/features/AdminPage/NewStreetcode/HistoryRelations/components/RelatedFigure.component.tsx
=> visible input & cleaner code

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.component.tsx, src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx
=> Add links for SideTab

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawerItem/HeaderDrawerItem.component.tsx, src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.styles.scss, src/features/AdminPage/NewStreetcode/HistoryRelations/components/InputPanel.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/components/RelatedFigure.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/components/RelatedFigureList.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/streetcode/streetcode-types.model.ts
=> Create street code/danya

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.styles.scss
=> Refactore Donates Modal

src/app/common/components/modals/Lightbox/Lightbox.component.tsx, src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss
=> adaptives for lightbox

src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss, src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
=> Fixed styles in tablet

src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss, src/app/layout/ModalWrapper.component.tsx
dev
Fixing arrow and Interesting fact modal imports issue.
Fixed imports.
=> [HOTFIX] Small fixes after merge

src/app/stores/related-terms-store.ts, src/app/stores/term-store.ts, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx, src/features/AdminPage/TermDictionary/TermDictionary.component.tsx
dev
Creating on spot was an issue.
Added creating return result.
=> [FIX] Fix create for terms

src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
=> Support us chack box fix

src/app/common/utils/base64ToUrl.utility.ts, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
=> [FIX] Interesting fact view

src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
=> fixed checkbox styles

src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.component.tsx
=> fix timeline

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.styles.scss
=> Donates new modal fix

src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx
=> added support-us page

src/app/stores/streetcode-coordinates-store.ts, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/MapBlock/MapAdmin/MapAdmin.component.tsx, src/models/additional-content/coordinate.model.ts, src/models/streetcode/streetcode-types.model.ts
=> added create for streetcode coordinates

src/app/common/components/modals/InterestingFacts/InterestingFactsModal.component.tsx, src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
dev
Fixed styles after merge
ToDo
=> All fixes for streetcode page adaptivity

src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
=> Subtitle fix

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
dev
Fixed image problem on slides
ToDo
=> Fixed image problem

src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
=> datepicker-styles

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
=> tegs styles

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsAdminItem/InterestingFactsAdminItem.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx
=> wow-facts-admin-styles

src/features/AdminPage/NewStreetcode/HistoryRelations/components/components.styles.scss, src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss, src/features/AdminPage/NewStreetcode/SubtitileBlock/SubtitleBlock.component.tsx
=> fix border shadow and some more styles

src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtn/PartnersBtn.styles.scss, src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.styles.scss, src/features/AdditionalPages/PartnersPage/Partners.styles.scss, src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
=> Partners fix

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/MainDrawerHeaderItems/MainDrawerList.component.tsx, src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
=> Added routes to the menu and fixed bgcolor

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
=> Donate modal conf and style fix

src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx
dev
ToDo
add redirect to partners page
ToDo
ToDo
=> add redirect to partners page

src/features/StreetcodePage/TickerBlock/Ticker.component.tsx, src/features/StreetcodePage/TickerBlock/Ticker.styles.scss
=> Stop ticker on hover

src/features/AdminPage/StreetcodesTable/SearchMenu.component.tsx, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
=> fixed buttons

src/features/AdminPage/AdminModal.styles.scss, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss, src/features/AdminPage/NewStreetcode/MapBlock/MapAdmin/MapAdmin.styles.scss, src/features/AdminPage/NewStreetcode/MapBlock/StatisticsToponymsAdmin/StatisticsToponymsAdmin.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss
=> Checkbox styles admin add

src/features/AdminPage/AdminPage.component.tsx, src/features/AdminPage/AdminPage.styles.scss, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss, src/features/AdminPage/PageBar/PageBar.component.tsx, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
=> Admin panel layout

src/features/AdditionalPages/NotFoundPage/NotFound.component.tsx
=> redirect to main page

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> fix-button-width-margin

src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/PartnersBlock/Partners.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx, src/features/StreetcodePage/Streetcode.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx, src/features/StreetcodePage/TickerBlock/Ticker.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx
dev
ToDo
Hide empty blocks
ToDo
ToDo
=> add-display-none

src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
=> added reloading in Related History block

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
=> admin inputnumberFix

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
=> minor changes

src/app/api/sources/sources.api.ts, src/app/common/constants/api-routes.constants.ts, src/features/AdminPage/ForFansPage/ForFansMainPage.style.scss, src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
=> Hot fix sources

src/features/AdminPage/NewStreetcode/MapBlock/MapAdmin/MapAdmin.component.tsx
=> fixing the map in the admin panel

src/features/AdminPage/PageBar/PageBar.component.tsx
=> [HOTFIX] For fans link

src/app/stores/image-loader-store.ts, src/features/StreetcodePage/Streetcode.component.tsx
=> deleted console logs

src/app/common/constants/frontend-routes.constants.ts, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/PageBar/PageBar.component.tsx
=> [HotFix] Fixing new streetcode route

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
=> bug-fix input number

src/app/common/components/AudioPlayer/AudioPlayer.component.tsx, src/app/common/components/modals/ListenText/ListenText.component.tsx, src/app/stores/partners-store.ts, src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss, src/features/AdminPage/PartnersPage/Partners.component.tsx, src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.component.tsx, src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
=> Partner audio fix

src/app/api/transactions/transactLinks.api.ts, src/app/common/components/AudioPlayer/AudioPlayer.component.tsx, src/app/common/components/modals/ListenText/ListenText.component.tsx, src/app/common/constants/api-routes.constants.ts, src/app/stores/newstreetcode-info-store.ts, src/app/stores/partners-store.ts, src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.style.scss, src/features/AdminPage/NewStreetcode/ARBlock/ARBlock.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss, src/features/AdminPage/PartnersPage/Partners.component.tsx, src/features/SlickSlider/SlickSlider.component.tsx, src/features/SlickSlider/SlickSlider.styles.scss, src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.component.tsx, src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss, src/features/StreetcodePage/QRBlock/QR.component.tsx, src/features/StreetcodePage/QRBlock/QR.styles.scss, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx, src/models/streetcode/streetcode-types.model.ts
=> Ar effect admin panel

src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
=> fixed positioning bug

src/app/common/components/FileUploader/FileUploader.component.tsx
=> fixed uploader (for deleting img)

src/features/SlickSlider/SlickSlider.styles.scss, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
=> removed important from slick slider class

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> Required field for category in create streetcode

src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx, src/models/news/news.model.ts
=> Added field for creation date in modal and display on a table

src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
=> fix fact single

src/app/router/Routes.tsx, src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx, src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
=> Fix support us page styling

src/app/common/components/modals/Tags/TagsModal.component.tsx, src/app/common/components/modals/Tags/TagsModal.styles.scss, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss, src/app/stores/root-store.ts, src/app/stores/streetcodes-bytag-store.ts
=> Fixed tag modal.

Dockerfile
=> docker file

src/app/api/donates/donation.api.ts, src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx, src/features/MainPage/MainPage.component.tsx, src/models/feedback/donation.model.ts
=> Fix donation

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
=> [FIX] Linked main page

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.styles.scss, src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss, src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss, src/assets/sass/variables/_variables.colors.scss, src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.styles.scss, src/features/AdditionalPages/NotFoundPage/NotFound.component.tsx, src/features/AdditionalPages/NotFoundPage/NotFound.styles.scss, src/features/AdditionalPages/PartnersPage/ModalButtons/DonateBtn/DonateBtnRectangle.styles.scss, src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtn/PartnersBtn.styles.scss, src/features/AdditionalPages/PartnersPage/Partners.styles.scss, src/features/AdditionalPages/PrivatePolicyPage/PrivatePolicy.styles.scss, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss, src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx, src/features/AdminPage/TermDictionary/TermDictionary.component.tsx, src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx, src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
=> fixed drawer, background, several buttons

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fixed data.stopPropagation() is not a function on Streetcode Publish and Draft

src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
=> Created validation for Url, fixed problem with photos

src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx, src/features/AdminPage/NewsPage/News.component.tsx
=> Fixed code related with mobx

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminItem/ForFansAdminItem.component.tsx, src/features/AdminPage/NewStreetcode/HistoryRelations/components/RelatedFigure.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsAdminItem/InterestingFactsAdminItem.component.tsx, src/features/AdminPage/NewStreetcode/MapBlock/MapAdmin/MapAdmin.component.tsx, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineItem/NewTimelineItem.component.tsx
=> Confirmation modal for delete

src/app/router/Routes.tsx
=> remove protected from dictianary route

src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx
=> Fix popup image

src/app/stores/toponym-store.ts, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.component.tsx
=> fix tags and timelines first slide

src/app/common/components/CopyWithCopyright.component.tsx, src/app/layout/app/App.component.tsx
=> copyright component

src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
cleared error on the admin page streetcodes table
=> Cleared error related with render

src/assets/images/main-page/headerRectMobile.svg, src/features/MainPage/Heading/Heading.component.tsx, src/features/MainPage/Heading/Heading.styles.scss
Added ternary operator so it would display properly on mobile screens and added @media for SCSS classes
=> Main heading adaptive

src/features/StreetcodePage/SourcesBlock/Sources.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Fixed gaps on tablets and phones and centered them. Added slider for screen 1024 - 1200 without dots
=> Sources slider items fix

src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
=> Donates page underline and buttons logic fix

src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Hot Fix, where I created a local state for the image and set it in case of successful upload and setting to undefined in case of deleted image
=> Fixed bug related with image creation

src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx, src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss, src/features/MainPage/NewsSlider/NewsSlider.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
=> Instagram and News block adaptives for main page

src/app/router/Routes.tsx
=> added NotFoundPage for all not existing endpoints

src/features/AdditionalPages/NewsPage/News.component.tsx, src/features/AdditionalPages/NewsPage/News.styles.scss
=> fixed situation when image was bigger then text and page just broke, and fixed paddings on mobile

src/app/common/components/modals/Terms/AddTerm/AddTermModal.component.tsx, src/app/common/components/modals/Terms/DeleteTerm/DeleteTermModal.component.tsx, src/app/common/components/modals/Terms/EditTerm/EditTermModal.component.tsx, src/features/AdminPage/TermDictionary/TermDictionary.component.tsx
dev
Validation wasn't present in modal terms
Added validation to all modals.
Entered new term with both empty inputs or with one present input. Validation works
=> Added validation to terms

src/features/StreetcodePage/QRBlock/QR.styles.scss
=> Changed spacing between QRBlock and sources

src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/media/art.model.ts, src/models/media/image.model.ts, src/models/streetcode/streetcode-types.model.ts
=> remove image, only send image id

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/streetcode/streetcode-types.model.ts
=> Fix update create

src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx
=> [Fix/419]Fix art modal window input fields

src/app/common/components/modals/InterestingFacts/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/InterestingFactsBlock.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/QRBlock/QR.component.tsx
=> Replace -- to - =)

src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx, src/features/AdditionalPages/SupportUsPage/SupportUs.styles.scss
=> Fixed 'Copy check' button and added a copy message

src/features/StreetcodePage/Streetcode.component.tsx
dev
https://github.com/ita-social-projects/StreetCode_Client/issues/379
The redirect from non-existing streetcodes to 404 was not available. There was infinity loop instead of redirect.
Added redirect with one function.
=> [Fixed bug] 404 redirect

src/features/ProgressBar/NavigableBlockWrapper.component.tsx
dev
[Issue](https://github.com/ita-social-projects/StreetCode_Client/issues/400)
Reworked part of previous code.
ToDo
=> fixed sections name

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/streetcode/streetcode-types.model.ts
dev
Publish button doesn't work
Change some code for correct working
ToDo
=> Fix streetcode publish button

src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss, src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx, src/models/partners/partners.model.ts
Fixed an issue with key fields and improved the UI for creating social links. A lot of changes, because I used _Prettier_ to make the code look better.
=> Modals validation and UI improvements

src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fix errors admin panel

src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
=> Display the video if there is a link

src/app/common/components/ProtectedComponent.component.tsx, src/app/stores/facts-store.ts, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.component.tsx, src/models/media/image.model.ts, src/models/streetcode/streetcode-types.model.ts, src/models/streetcode/text-contents.model.ts
=> Fix wowfact

src/features/AdminPage/NewStreetcode/ArtGallery/components/ArtGallery/ArtGalleryAdminStyles.styles.scss
=> Fix art preview content height

src/app/common/components/modals/Partners/PartnersModal.styles.scss, src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.styles.scss
=> border-fix

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
=> AR button fix

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
=> Added translation for Tiny modals

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/ForFansPage/ForFansPage/ForFansPage.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/PageBar/PageBar.component.tsx
=> Added "Додати нову категорію..." button on forFans modal

src/app/common/components/ProtectedComponent.component.tsx, src/app/stores/create-update-media-store.ts, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/models/media/image.model.ts, src/models/streetcode/streetcode-types.model.ts
=> Nk 446 streetcode photo

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/streetcode/streetcode-types.model.ts
=> fix publish and draft date

src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fix update

src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
=> implemented confirmation window when changing streetcode status

src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx, src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss
dev
[Issue](https://github.com/ita-social-projects/StreetCode_Client/issues/457)
Fixed dots reflection for screens with widht < 380, also added instagram button for mobile devices as on figma
ToDo
=> added instagram button, fixed dots

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/ForFansPage/ForFansPage/SourceItem.tsx
=> Translated into Ukrainian

src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/DownloadStyles.styles.scss
=> Art Gallery multi delete. Recreating pull request after mistaken merge.

src/app/common/components/TagList/TagList.component.tsx, src/app/common/components/TagList/TagList.styles.scss
=> fixed display of the tag modal window on mobile devices

src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
=> [Admin/Chronology] Changed max length of title to 26

src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
=> Donate checkbox align and blue borders fix

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
… on "додати нову категорію" the category name was not displayed
dev
ToDo
ToDo
ToDo
=> fix name display of category after adding on admin page

src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx
=> Added translation for art gallery modal

src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss
=> changed word wrap for chronology item block

src/app/api/streetcode/streetcodes.api.ts, src/app/common/constants/api-routes.constants.ts, src/app/layout/header/HeaderBlock.styles.scss, src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fix related figures admin

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> fix toolbar

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss, src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
=> Wow fact for fans adaptive fix

src/features/AdminPage/NewStreetcode/HistoryRelations/HistoryRelations.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx, src/models/streetcode/streetcode-types.model.ts
=> 404 update create streetcode nk

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> 489 fix reloadredirect confirmation

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
When creating/editing a streetcode added a check to see if such a link already exists. Also fixed an error with the display of the first and last name if we select "Person". Also removed the Check number button. Now the index is checked automatically
=> Duplicate url fix, Check Index fix

src/app/common/hooks/scrolling/useOnScreen.hook.ts
dev
ToDo
Fix catalogue loading
Catalogue loading is now working
https://github.com/ita-social-projects/StreetCode_Client/assets/92052144/7def24f9-783a-447f-b99a-00ef82f37c9f
=> fix catalogue loading

src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
=> Data format fix

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
Issue↓
https://github.com/ita-social-projects/StreetCode/issues/417dev
ToDo
ToDo
ToDo
=> Added character counter

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/456
ToDo
ToDo
ToDo
=> Added tags list sorting in alphavbetical order

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
=> fixed char limit on admin page in text block

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/StreetCodeBlock/StreetCodeBlock.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/413
ToDo
ToDo
ToDo
=> No scrolling when clicking on "Назва" (chronology)

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
=> Fixing displaying text on text editor on admin page

src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.style.scss
dev
* https://github.com/ita-social-projects/StreetCode/issues/423
ToDo
ToDo
ToDo
=> 423 adminchronology block  context symbolscounter

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/PreviewImageModal/PreviewImageModal.styles.scss
completed 6 tickets:
https://github.com/ita-social-projects/StreetCode/issues/457
https://github.com/ita-social-projects/StreetCode/issues/428
https://github.com/ita-social-projects/StreetCode/issues/448
https://github.com/ita-social-projects/StreetCode/issues/449
https://github.com/ita-social-projects/StreetCode/issues/430
https://github.com/ita-social-projects/StreetCode/issues/454
=> Fix characters limit to the fields.

src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
dev
https://github.com/ita-social-projects/StreetCode/issues/410
ToDo
ToDo
ToDo
=> Fix streetcode link background

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> Made a localization for "Для фанатів" modal window

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
https://github.com/orgs/ita-social-projects/projects/21/views/1?pane=issue&itemId=34044873
=> fixed display of name and surname

package.json, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
dev
No error messages when pasting other links than YouTube.
Added error message with new preview and links.
Test different links for input in the field.
=> 488 admin page video input validation

package.json, src/app/api/streetcode/text-content/texts.api.ts, src/app/common/constants/api-routes.constants.ts, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx, src/models/streetcode/text-contents.model.ts
dev
#478
Preview was not working.
Add text to the field above and press `Попередній перегляд`
=> 478 admin text and video block an error is thrown when previewing the main text

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
dev
[Issue](https://github.com/ita-social-projects/StreetCode_Client/issues/470)
ToDo
ToDo
=> Modals for delete

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
=> Vlad character limit for authorship and for fans

src/features/StreetcodePage/Streetcode.styles.scss
=> fixed displaying load gif on wide monitors

src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
=> Fix to unlock date filed after selected firsting date

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
=> Fixed image description saving

src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
dev
https://github.com/orgs/ita-social-projects/projects/21/views/1?filterQuery=Andrii&pane=issue&itemId=33172645
ToDo
=> Fix arts limit

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
=> fixed updating streetcode streetcode with video

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/530
ToDo
ToDo
ToDo
=> Empty alias isn't displayed

src/assets/sass/variables/_variables.colors.scss, src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSlider.styles.scss, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss, src/features/MainPage/TeamSlider/TeamComponent.component.tsx, src/features/MainPage/TeamSlider/TeamComponent.styles.scss, src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx, src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
dev
Lack of adaptives for mobile, tablet
Added adaptives for tablet and mobile.
ToDo
=> adaptives for team, streedcode slidersNew adaptives sliders

src/features/StreetcodePage/TextBlock/SearchTerms/SearchTerms.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
=> fix text load

src/app/common/utils/selectValidation.utility.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/532
ToDo
ToDo
ToDo
=> 532 tags validation UI

src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx, src/app/common/components/modals/Survey/SurveyModal.component.tsx
=> add survey button and change links open logic

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/SearchBlock/SearchResultItem/SearchItem.component.tsx
=> search field fix

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fixed text updating

src/app/layout/app/App.styles.scss, src/features/AboutUsPage/AboutUsHeaderText/AboutUsHeaderText.component.tsx, src/features/AboutUsPage/AboutUsHeaderText/AboutUsHeaderText.styles.scss, src/features/AboutUsPage/AboutUsPage.component.tsx, src/features/AboutUsPage/AboutUsPage.styles.scss
=> Add header block

src/app/common/constants/api-routes.constants.ts, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/models/streetcode/streetcode-types.model.ts, src/models/transactions/transaction-link.model.ts
dev
#515
Editing of the AR link was not working on admin page.
Working functionality.
Edit the ar link.
=> 515 Fix AR update

src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
=> Fixed gray square with the year shift

src/features/ProgressBar/NavigableBlockWrapper.component.tsx, src/features/ProgressBar/ProgressBar.component.tsx, src/features/ProgressBar/ProgressBar.styles.scss, src/features/ProgressBar/ProgressBarFill/ProgressBarFill.styles.scss, src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
dev
User story: https://github.com/ita-social-projects/StreetCode/issues/77
Test Case: https://github.com/ita-social-projects/StreetCode/issues/102
Bug: https://github.com/ita-social-projects/StreetCode/issues/475
ToDo
ToDo
=> Fixed and redesigned progress bar

src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
dev
https://github.com/ita-social-projects/StreetCode/issues/513
https://github.com/ita-social-projects/StreetCode/issues/514
ToDo
ToDo
ToDo
=> [Admin] System allows saving changes StreetCode without filling in 'Анімація' fields

src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
=> Fix displaying "грудень" in datepicker field on admin panel

src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss
=> Fixed wow fact photo display

src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
=> fix for slider for for fans block

src/app/stores/facts-store.ts, src/app/stores/image-store.ts, src/app/stores/news-store.ts, src/app/stores/sourceadmin-store.ts
=> added autoclear for appropriate Maps.

src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
=> Fixed display of non-existent link

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
=> For fans max limit hot fix

src/app/api/job/Job.api.ts, src/app/common/constants/api-routes.constants.ts, src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx, src/features/AdminPage/JobsPage/JobsModal/JobsModal.styles.scss, src/features/AdminPage/JobsPage/JobsTable/JobsTable.component.tsx, src/models/jobs/Jobs.model.tsx
=> added modal for admin pannel to add and update vacancy

src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
=> stash modal data

src/app/common/constants/screen-sizes.constants.tsx, src/assets/sass/variables/_variables.sizes.scss, src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.component.tsx, src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.styles.scss
=> add adaptives to vacancies modal

src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
=> Fixed preview of animation/b&w

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.styles.scss
=> Vlad sreetcodes adaptive fix

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
=> Made the modal not clickable on the phone version

src/app/common/components/TagList/TagList.component.tsx, src/app/common/components/TagList/TagList.styles.scss
=> Made non-actiive sretcode tags on tablets

src/app/stores/timeline-store.ts, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineItem/NewTimelineItem.component.tsx, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx, src/features/AdminPage/NewStreetcode/TimelineBlock/TimelineBlockAdmin.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx, src/models/timeline/chronology.model.ts
1. Fix saving timelines
2. All dates are saved in UTC
3. We do not lose hours when sent or retrieve ot
=> Timeline date fix

src/app/common/constants/screen-sizes.constants.tsx, src/assets/sass/variables/_variables.sizes.scss
=> add constants for screen width

src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/app/common/components/modals/Partners/PartnersModal.styles.scss
dev
[issue](https://github.com/ita-social-projects/StreetCode/issues/582)
ToDo
ToDo
=> added clear func for close button

src/app/stores/news-store.ts, src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
* https://github.com/orgs/ita-social-projects/projects/21/views/1?filterQuery=andrii&pane=issue&itemId=35501661
ToDo
ToDo
ToDo
=> News date fix

public/index.html
dev
Hotfix for backend url as env variable. Replaced relative path with absolute, which caused bugs in news and admin panel sections.
ToDo
ToDo
ToDo
=> hotfix: replace relative path with absolute for env-config.js

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.styles.scss
dev
* https://github.com/ita-social-projects/StreetCode/issues/478
ToDo
ToDo
ToDo
=> Message for the user when maintext is being loaded

docker-compose.yml
=> Change docker images to centralized repo

src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
Validation did not pass this partner link:
https://www.victims.memorial/
ToDo
ToDo
ToDo
=> Partners link validation hot fix

src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.component.tsx, src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.styles.scss, src/features/AdditionalPages/PartnersPage/Partners.component.tsx, src/features/AdditionalPages/PartnersPage/Partners.styles.scss
dev
* https://github.com/ita-social-projects/StreetCode/issues/590
ToDo
ToDo
ToDo
=> Added floating of the button

src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx
dev
https://github.com/orgs/ita-social-projects/projects/21?pane=issue&itemId=35659633
ToDo
ToDo
ToDo
=> Fix progress bar items clickable area

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
=> fixed redirect issue

src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
[[Admin] StreetCode published with invalid data in the field 'РОКИ'](https://github.com/ita-social-projects/StreetCode/issues/564)
dev
ToDo
ToDo
ToDo
=> added validation for date field admin panel

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> Categories hot fix

src/app/common/components/modals/ListenText/ListenText.styles.scss, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.style.scss
dev
[1 issue](https://github.com/orgs/ita-social-projects/projects/21/views/1?pane=issue&itemId=34662334)
[2 issue](https://github.com/orgs/ita-social-projects/projects/21/views/1?pane=issue&itemId=34662931)
1 commit for 1 issue, 2 for 2 issue
ToDo
=> Fix audio buttons

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
[* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)](https://github.com/ita-social-projects/StreetCode/issues/526)
=> fixed displaying text on the first click

src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx, src/features/AdminPage/TeamPage/TeamModal/TeamModal.styles.scss, src/features/AdminPage/TeamPage/TeamPage.component.tsx, src/models/team/team.model.ts
=> Revert "modal fix"

src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx, src/features/AdminPage/TeamPage/TeamModal/TeamModal.styles.scss, src/features/AdminPage/TeamPage/TeamPage.component.tsx, src/models/team/team.model.ts
Reverts ita-social-projects/StreetCode_Client#647
=> Revert "Revert "modal fix""

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
=> modified redirect

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
=> replaced "to" to "href"

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
=> super hot fix with page reload

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
Reverts ita-social-projects/StreetCode_Client#654
=> Revert "super hot fix with page reload"

src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
=> main page sort

src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
dev
ToDo
Now audio isn't required for streetcode create
ToDo
=> fix required audio

src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx, src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
dev
Bug fixing
[StreetCode page] Title of the description isn't centered with text #604
(https://github.com/ita-social-projects/StreetCode/issues/604)
and
[StreetCode page] Title of the description block stick to the page's border when resolution is from 786 to 769px#605
(https://github.com/ita-social-projects/StreetCode/issues/605)
ToDo
ToDo
=> Fixing bugs 604-605

src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
=> Fixed button size

src/features/AdditionalPages/NewsPage/News.styles.scss
=> Fixed button color on hover

src/features/MainPage/NewsSlider/NewsSlider.component.tsx, src/features/MainPage/NewsSlider/NewsSlider.styles.scss
=> Vlad news button

src/features/StreetcodePage/QRBlock/QR.component.tsx, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode_Client/issues/658
ToDo
ToDo
ToDo
=> Hyphen + hide block if no ar url

src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
=> Fixed news displaying

src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
=> fixed team modal

src/features/MainPage/StaticBanners/StaticBanner.styles.scss
https://github.com/ita-social-projects/StreetCode/issues/584
https://github.com/ita-social-projects/StreetCode/issues/574
=> fix styles

src/app/api/team/tickerString.api.tsx, src/app/common/constants/api-routes.constants.ts, src/features/AboutUsPage/AboutUsPage.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx, src/features/StreetcodePage/TickerBlock/Ticker.component.tsx
=> added ticker string to about us

src/features/AdminPage/TeamPage/TeamPage.component.tsx
=> position fix

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
=> Made modal window clickable

src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
=> Fixed input shift

src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss, src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.styles.scss
dev
[#642](https://github.com/ita-social-projects/StreetCode/issues/642)
ToDo
ToDo
ToDo
=> Change CSS StreetcodeCatalog

src/features/MainPage/TopCarousel/TopCarousel.component.tsx, src/features/MainPage/TopCarousel/TopCarousel.styles.scss
dev
* https://github.com/ita-social-projects/StreetCode_Client/issues/674
ToDo
ToDo
ToDo
=> Changed the speed

src/app/stores/streetcode-page-loader-store.ts, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Animation now supports a web format. Audion does not block loading no more.
ToDo
ToDo
ToDo
=> Streetcode page loading fix

src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
dev
Unhandled error on Main page due to Instagram request returning 500 status code
Add empty try-catch to catch the error. Component will not render if error received. 
Run npm start and visit main page. There should not be a default js modal window with unhandled error.
=> - add empty try-catch to make error handled on Main Page

src/features/StreetcodePage/TextBlock/AdditionalTextBlock/AdditionalTextBlock.styles.scss
=> Added underline for link

src/features/MainPage/TopCarousel/TopCarousel.styles.scss
dev
https://docs.google.com/spreadsheets/d/15QZa815p8dFcHokF341fszY2GAY59xYu0I5uBSHktTU/edit#gid=450234442
task on 73 line
ToDo
ToDo
ToDo
=> Fix for dots carousel

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode_Client/issues/662
ToDo
ToDo
ToDo
=> 662 clickable cards in blocks

src/app/common/components/modals/Donates/DonatesModal.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/656
ToDo
ToDo
ToDo
=> Fixed - in donates

src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
=> Remove loading video waiting

src/features/MainPage/Heading/Heading.component.tsx, src/features/MainPage/NewsSlider/NewsSlider.component.tsx
=> 683 main page redundant functionality in news block

src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
=> fixed scroll after first render

src/features/MainPage/TopCarousel/TopCarousel.styles.scss, src/features/SlickSlider/SlickSlider.styles.scss
dev
* All the dots under the banner need to be visible on mobile devices.
ToDo
ToDo
ToDo
=> Dots banner sliders

src/app/layout/app/slick-slider.overrides.scss, src/features/SlickSlider/SlickSlider.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
dev
* Rearranged dots displaying
ToDo
ToDo
ToDo
=> Fix dots mainpage sliders

src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.component.tsx
=> fix height after which button is visible

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
=> Fixed wowfact modal window opening

src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss, src/features/SlickSlider/SlickSlider.styles.scss, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
=> Vlad image cropping fix

src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
=> News display fix

src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx, src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
=> Fix main text

src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
=> very hot fix, chronology Title max length

src/app/api/team/positions.api.ts, src/app/common/constants/api-routes.constants.ts, src/features/AboutUsPage/TeamMembers/TeamMembers.component.tsx, src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
Reverts ita-social-projects/StreetCode_Client#725
=> Revert "sliders"

src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx
dev
* https://github.com/ita-social-projects/StreetCode/issues/687
ToDo
ToDo
ToDo
=> Changed long dash (—) to Word standard dash (–)

src/app/common/components/modals/Sources/SourcesModal.styles.scss
dev
* Aim: to fix sources modal displaying:
ToDo
ToDo
ToDo
=> Fixed text displaying in source modal

src/app/api/partners/partners.api.ts, src/app/common/constants/api-routes.constants.ts, src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.component.tsx, src/features/MainPage/PartnersBlockMain/PartnersBlockMain.component.tsx
=> Fix off screen images in partner block

src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.styles.scss
=> AR block centered on modile

src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
dev
If there is only a year and a month in the chronology, then write "лютий" instead of "лютого"
ToDo
ToDo
ToDo
=> Vlad month chronologi format fix

src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
dev
* To fix news url displaying in the left corner.
ToDo
ToDo
ToDo
=> Fixed news url displaying

src/app/common/components/modals/InterestingFacts/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx, src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
=> Allow webp format files to upload

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/LinkEditor.component.tsx
=> deleting requared rule to video filed

src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
dev
* To add alphabetical sorting of the partners dropdown list + change partners select logic in admin page.
ToDo
ToDo
ToDo
=> Partners admin

src/features/AboutUsPage/TeamMembers/TeamMembers.component.scss, src/features/AboutUsPage/TeamMembers/TeamMembersList/TeamMemberList.styles.scss, src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamMembersSlider.component.tsx
=> border delete for sliders

src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
=> fixed modal

src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
dev
* partners should move automatically (every 2.5 secs now)
* movement stops when hovering
* the user can scroll manually
ToDo
ToDo
ToDo
=> Fixed partners slider scroll

src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/features/AdditionalPages/ContactUsPage/MainBlock/ContactForm/ContactForm.component.tsx, src/index.scss
=> Make handling email message sending response

public/index.html, src/features/AdditionalPages/PartnersPage/PartnersBlock/PartnersBlock.component.tsx, src/features/MainPage/MainPage.component.tsx, src/features/MainPage/NewsSlider/NewsSlider.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/MainPage/TeamSlider/TeamComponent.component.tsx, src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.component.tsx
dev
Fix extra requests on main page:
-partners image requests
-news image requests
-team image requests
-tinymce extra request
ToDo
ToDo
ToDo
=> Fix extra requests on main page

src/app/common/components/FileUploader/FileUploader.component.tsx, src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx, src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx
dev
Add grey masks for source images
ToDo
ToDo
ToDo
=> Fix add grey filter for sources

src/features/AdditionalPages/PartnersPage/PartnersItem/PartnersItem.component.tsx, src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerContent/PartnerContent.component.tsx
=> Fix partners mini logo

src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.component.tsx
=> fix partners block in streetcode page

src/features/StreetcodePage/Streetcode.component.tsx
=> qr-id-hot-fix

public/index.html
=> fix titymce text fields in streetcode edit page

src/assets/sass/mixins/_utils.mixins.scss, src/features/AboutUsPage/Founders/Founders.component.tsx, src/features/AboutUsPage/TeamMemberCard/TeamMemberCard.component.tsx, src/features/AboutUsPage/TeamMemberCard/TeamMemberCard.styles.scss, src/features/AboutUsPage/TeamMemberCard/TeamMemberLinks/TeamMemberLinks.component.tsx, src/features/AboutUsPage/TeamMembers/TeamMembersList/TeamMemberList.component.tsx, src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamMembersSlider.component.tsx
Fix about us slider:
- when only one person is on mobile about us slider, it's not duplication now (you see just one card)
- when different images and text amount are on different cards, they have same size anyway
=> - fix image duplication on mobile

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx
dev
fix unnessary grey filter for streetcode animation
ToDo
ToDo
ToDo
=> fix unnessary grey filter for streetcode animation

src/features/AboutUsPage/TeamMembers/TeamMembers.component.scss, src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx, src/features/AboutUsPage/Vacancies/Vacancies.component.tsx, src/features/AboutUsPage/Vacancies/Vacancies.styles.scss, src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.syles.scss
When you go to about-us page on mobile and scroll down to slider, navigation arrows are normal (not squeezed)
=> - fix swiper navigation on mobile

src/app/common/components/modals/Tags/TagsModal.styles.scss, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss, src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss, src/features/StreetcodePage/MainBlock/MainBlock.styles.scss, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss, src/features/StreetcodePage/MapBlock/CheckBox/CheckBox.styles.scss, src/features/StreetcodePage/MapBlock/MapBlock.styles.scss, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss, src/features/StreetcodePage/SourcesBlock/Sources.styles.scss, src/features/StreetcodePage/Streetcode.styles.scss, src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
=> Fix design streetcode page

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
dev
fix tox text
ToDo
ToDo
ToDo
=> fix tox text

public/index.html, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> fix tox in streetcode edit window

src/app/common/components/FileUploader/FileUploader.component.tsx, src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/ArtGallery/components/Download.component.tsx
=> Revert "Allow multiple file uploads in art gallery"

src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
1. *** add in news (admin page ) this text :** 
Go, ГО! або як зареєструвати громадську організацію та не вигоріти? Наш досвід реєстрації. Наша історія. Лови лайфхаки, щоби шлях реєстрації твого ГО був коротший, ніж текст про наш досвід:
Максимально уважно читай ЗАКОН УКРАЇНИ про громадські об'єднання, особливо в частині «Мета та Цілі організації». Ну щоб буква в букву Закона. Це не жарт. Державні реєстратори — серйозні люди.
Завжди став лапки в назві, навіть в назві англійською. Оце бісило, правда.
Перевір відповідність повної та скороченої назви твого ГО українською та англійською, щоб в усіх документах ОДНАКОВО. МИ теж не любимо одноманітність, але ж.
Попроси дівчат (хлопців не бачили просто) підказати та внести незначні правки, наприклад, в заяві в момент першої подачі документів. Де …
=> fix word breaking and overflowing

src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
* scroll down to team members slider on main page
* images should be with normal dimensions (not stretched or squeezed)
=> add object-fit: cover to all screens, not only mobiles

public/index.html, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextPreview/TextPreview.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
=> Deleting a history map

src/app/common/components/TagList/TagList.styles.scss, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> tabs on streetcode page fixed

src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
=> Chronology dates before 1 may 1984 fix

src/features/AdminPage/ForFansPage/ForFansMainPage.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
dev
Fix to Incorrect displaying categories in the category list #804
ToDo
ToDo
=> Displays categories in the category list valerii

src/features/AdditionalPages/PartnersPage/Partners.styles.scss
Now partners background looks up to the figma design(desktop).
=> Fix partners background

src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
=> Fix space between related figure items in a column

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx, src/app/layout/header/HeaderSkeleton/HeaderSkeleton.styles.scss
=> Fix search

src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
=> Open news details in the new tab

src/features/AdminPage/NewStreetcode/MainBlock/DragableTags/DragableTags.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Streetcode's tags indexation on create and on update

Dockerfile, docker-compose.yml, nginx/nginx.conf, templates/default.conf.template
=> enable https

docker-compose.yml
=> fix compose

src/app/common/components/modals/Sources/SourcesModal.styles.scss, src/features/AdditionalPages/NewsPage/News.styles.scss, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
dev
* Marked/nembered list is displayed properly
* The news text block on main page if displayed properly (even with short title)
ToDo
ToDo
ToDo
=> News major fix

src/features/AdminPage/Analytics/Analytics.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
=> Make animation field non-required and fix associated code

src/app/layout/footer/Footer.component.tsx
=> add link to google drive

src/features/StreetcodePage/PartnersBlock/Partners.styles.scss
=> streetcode-partners-fix

src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss
=> forFansCenterTitle: fix title in for fans block, center text

src/features/AdminPage/Analytics/Analytics.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Reverts ita-social-projects/StreetCode_Client#800
=> Revert "Make animation field non-required and fix associated code"

src/features/StreetcodePage/Streetcode.component.tsx
=> art-galery-load-fix

src/features/AdminPage/Analytics/Analytics.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
Reverts ita-social-projects/StreetCode_Client#847
=> Revert "Revert "Make animation field non-required and fix associated code""

src/features/StreetcodePage/PartnersBlock/PartnerItem/PartnerItem.styles.scss
=> partnerLogo-fix

templates/default.conf.template
=> max image size fix

src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
dev
fix problem with text, that is not showed in main text and authorship
ToDo
ToDo
ToDo
=> fix problem with text, that is not showed in main text and authorship

src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Reverts ita-social-projects/StreetCode_Client#864
=> Revert "Develop"

src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
Reverts ita-social-projects/StreetCode_Client#862
=> Revert "fix problem with text, that is not showed in main text and authorship"

src/features/StreetcodePage/DonateBtn/DonateBtn.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx
=> survey and timeline fix

src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPositionSlider.styles.scss, src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
dev
add possibility to navigate with clicking on options
ToDo
ToDo
ToDo
=> add possibility to navigate with clicking on options

src/features/StreetcodePage/HeadingBlock/BlockHeading.component.tsx, src/features/StreetcodePage/HeadingBlock/BlockHeading.styles.scss, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> block heading fixed

src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx, src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
=> Change roll up text button on streetcode mobile page

public/index.html
=> google-analytics

src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
=> vakakakancii fix

public/index.html
Reverts ita-social-projects/StreetCode_Client#876
=> Revert "hot-fix"

public/index.html
=> Google tag

src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
=> small add fixes

src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx, src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx
dev
add possibility to navigate by clicking on facts
ToDo
ToDo
ToDo
=> add possibility to navigate by clicking on facts

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> Fixed unavailabilbity of previous categories in for fans admin modal

src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx
=> fix slider

src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.styles.scss
delete gif in qr block
dev
ToDo
ToDo
ToDo
=> delete gif in qr block

src/app/stores/news-store.ts, src/features/AdminPage/NewsPage/News.component.tsx
=> Sort news by date in admin panel

src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
=> Sort source categories by name in Admin panel

src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx, src/features/AdminPage/JobsPage/JobsModal/JobsModal.styles.scss
dev
fix not changing text in description input when you change vacancy
fix bugs with description input length
add styles for description
ToDo
ToDo
ToDo
=> fix vacancies modal

src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx, src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
=> joinTheTeamBtn_fix: fix button click

src/app/common/components/modals/Donates/DonatesModal.styles.scss
dev
* Before:
**To fix styles.**
ToDo
ToDo
ToDo
=> Fixed donates checkbox styles in modal

src/features/AdditionalPages/PartnersPage/Partners.styles.scss, src/features/AdditionalPages/PartnersPage/Title/Title.styles.scss
=> Partners fonts fix

src/features/MainPage/NewsSlider/NewsSlider.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
dev
add possibility to redirect to news with click
ToDo
ToDo
ToDo
=> add possibility to redirect to news with click

src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx
=> open link in additional text in the new tab

src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
dev
ToDo
Change StreetcodeCatalog.component.tsx
ToDo
=> The correct display of the sun icon in the Streetcode catalog has been fixed

src/features/SlickSlider/SlickSlider.styles.scss
=> make wow-facts buttons visible

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/HeaderSkeleton/HeaderSkeleton.styles.scss, src/app/layout/header/SearchBlock/SearchBlock.component.tsx, src/app/layout/header/SearchBlock/SearchBlock.styles.scss, src/app/layout/header/SearchBlock/SearchResultItem/SearchItem.component.tsx, src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx, src/models/filters/streetcode-filter.model.ts
=> Fix search streetcode

Jenkinsfile
=> notification fix

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> Fixed image card displaying for resolution from 381 to 360

src/features/MainPage/Heading/Heading.styles.scss, src/features/MainPage/InstagramBlock/InstagramBlock.styles.scss, src/features/MainPage/NewsSlider/NewsSlider.styles.scss, src/features/MainPage/PartnersBlockMain/PartnersBlockMain.styles.scss, src/features/MainPage/TeamSlider/TeamComponent.styles.scss, src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
dev
* To fix indentations between titles of blocks and blocks + make proper distances between squares (in block titles) and title **on mobile**.
ToDo
ToDo
ToDo
=> Fixed indentations and other minor styles

src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionSeventh/SectionSeventh.component.tsx
=> Privace policy space fix

src/app/stores/streetcodes-catalog-store.ts, src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
Change loading "sun" behavior in catalog page. Not it works in a right way. Issue: #909
=> Loading "sun" works in a right way in catalog page

src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
ticket on board with the bug: https://github.com/ita-social-projects/StreetCode/issues/774
=> make images appearing smoother

src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx, src/features/AdminPage/NewStreetcode/TextBlock/TextForm/AdditionTextBlock/AdditionalTextBlockAdminForm.component.tsx, src/features/MainPage/NewsSlider/NewsSlider.component.tsx, src/features/SlickSlider/SlickSlider.styles.scss
1. Fixed problem with text, that isn't showed in text and authorship on admin page:
2. Made the same style for all slider buttons:
3. If one news is displayed, add posibility to open news with click.
=> fix problem with text, that isn't showed in text and authorship on admin page and two small fixes

src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx, src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
**Added "Стріткоди" caption on the streetcode catalog page in right upper corner.**
on mobile:
=> add caption to the streetcode catalog page

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/QRBlock/QR.component.tsx
=> made the whole 'Оживити картинку' button clickable

src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
dev
[Issue](https://github.com/ita-social-projects/StreetCode/issues/586)
ToDo
ToDo
=> added limit for news text

src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/app/layout/header/HeaderDrawer/HeaderDrawer.styles.scss
=> Burger menu slider dot fix

src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx
=> Fixed the navigation of tags slider by keyboard arrows

src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.styles.scss
=> Tags clickable space area fix

src/app/layout/header/HeaderBlock.styles.scss
=> made the header style the same as on figma

src/features/StreetcodeCatalogPage/StreetcodeCatalog.styles.scss
=> Fixed mobile streetcodes catalog to display 2 streetcode cards per row

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/features/AboutUsPage/Founders/Founder/FounderCard/FounderCard.component.tsx, src/features/AboutUsPage/Founders/Founders.component.tsx, src/features/AboutUsPage/TeamMemberCard/TeamMemberLinks/TeamMemberLinks.component.tsx, src/features/AdditionalPages/SupportUsPage/SupportUs.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.component.tsx, src/features/StreetcodePage/SourcesBlock/Sources.component.tsx, src/features/StreetcodePage/TextBlock/TextBlock.component.tsx
dev
* When fixing the problem with opening third-party links in the fan block (or any other that uses TinyMCE, such as authorship), you need to recreate the old links in admin panel to open it in a new tab.
ToDo
ToDo
ToDo
=> Links to third-party resources open in a new tab

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
=> Made the text under the streetcode's card clickable

src/features/AdditionalPages/PartnersPage/PartnersItem/PartnersItem.styles.scss
[#962](https://github.com/ita-social-projects/StreetCode_Client/issues/962)
ToDo
Add paddings to partners img
=> Add paddings to partners img

src/features/ProgressBar/ProgressBar.component.tsx
=> Fixed vertical progress bar scrolling on mouse clicking

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.styles.scss, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
=> Made the words 'персональних даних' clickable

src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/ContactForm/ContactForm.styles.scss, src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/app/common/components/modals/Partners/PartnersModal.styles.scss, src/app/router/Routes.tsx
[The user can enter any characters in the e-mail field#599](https://github.com/ita-social-projects/StreetCode/issues/599)
Notification in the partners' email field was added
=> Add notification in the partners' email field

src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
=> Fixed styles for streetcode slider in tablet and mobile mode

src/features/StreetcodePage/QRBlock/QR.component.tsx, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
=> AR new text

package.json, src/app/common/hooks/stateful/useClickOutside.hook.ts, src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/HeaderSkeleton/HeaderSkeleton.component.tsx, src/app/layout/header/HeaderSkeleton/HeaderSkeleton.styles.scss, src/app/layout/header/SearchBlock/SearchBlock.component.tsx, src/app/layout/header/SearchBlock/SearchBlock.styles.scss, src/app/layout/header/SearchBlock/SearchResultItem/SearchItem.component.tsx, src/app/layout/header/SearchBlock/SearchResultItem/SearchItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx
=> Fix the search dropdown 

src/app/common/components/CardText/CardText.component.tsx, src/app/common/components/CardText/CardText.styles.scss, src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.component.tsx, src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.syles.scss, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss
Please check these for components to correspond design in figma v1 design:
- News slider item on main page
- Streetcode card on main page
- Vacancy on about us page
- Wow fact in streetcode
=> Create shared card text component

public/index.html
=> add google analytics

src/app/common/hooks/scrolling/useScrollToTop.hook.ts, src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx, src/features/AdditionalPages/NewsPage/News.component.tsx
=> Open pages from the beginning of the page

src/features/ProgressBar/ProgressBar.styles.scss
=> Now progress bar is visible from 1448px to 1025px

src/app/common/components/FileUploader/FileUploader.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/PreviewFileModal/PreviewFileModal.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Add filter instead of gif on streetcode page
dev
ToDo
ToDo
ToDo
=> Add filter instead of gif

src/app/common/components/CardText/CardText.styles.scss
=> set display to inline in cardText

docker-compose.yml
=> Added restart policy for docker containers in docker-compose.yml

src/features/AdditionalPages/PrivatePolicyPage/Title/Title.component.tsx
Fix issue: [Політика конфіденційності] Does not redirect the user to the main page of the site #847
Fix Private Policy Page
=> Fix issue 847. Fix StreetCode Url Reference

src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
Fix issue #842
Fix Sources Styles
=> Fix Sources Styles issue 842

docker-compose.yml
=> add aspnetcore env

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
dev
Ticket #748
Fix saving wow facts without fully donloaded image
ToDo
ToDo
ToDo
=> fix saving wow facts without fully donloaded image

src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
=> News modal date and image are set to required

src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/ContactForm/ContactForm.styles.scss, src/app/common/components/modals/ContactUsModal/ContactUsModal.component.tsx, src/app/common/components/modals/ContactUsModal/ContactUsModal.styles.scss
=> fix contact us modal

src/app/api/streetcode/streetcodes.api.ts, src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/ContactForm/ContactForm.styles.scss, src/app/common/components/modals/ContactUsModal/ContactUsModal.component.tsx, src/app/common/components/modals/ContactUsModal/ContactUsModal.styles.scss, src/app/common/utils/paginateRequest.tsx, src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainBlock/DatePickerPart.component.tsx, src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSlider.styles.scss, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss, src/models/timeline/chronology.model.ts
=> Merge develop to master

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/SearchBlock/SearchBlock.component.tsx, src/app/layout/header/SearchBlock/SearchBlock.styles.scss
=> 868 search the "no results" message always appears

src/app/layout/header/HeaderBlock.component.tsx, src/app/layout/header/HeaderBlock.styles.scss, src/app/layout/header/SearchBlock/SearchBlock.component.tsx, src/app/layout/header/SearchBlock/SearchBlock.styles.scss
* fixed popover styles
* fixed the No results message styles
* hide the No results message during the query execution
dev
ToDo
ToDo
ToDo
=> 868 search the "no results" message always appears (#1023)

src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
=> Fixed partner modal save button for editing

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
dev
fix third card(for connections) on streetcode page
Before:
After:
ToDo
ToDo
ToDo
=> fix third card(for connections) on streetcode page

src/app/stores/news-store.ts, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
Ticket (but only for news modal, NOT all modals): https://github.com/ita-social-projects/StreetCode/issues/940
=> fix news modal from closing when request isn't completed yet

src/features/SlickSlider/SlickSlider.styles.scss, src/features/StreetcodePage/SourcesBlock/SourceItem/SourceItem.styles.scss, src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
#879
Hide slide categories outline
=> Hide slide categories outline

src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.component.tsx
=> fix scrolling to the main text when open streetcode page

package.json, public/index.html, src/features/AdditionalPages/NewsPage/News.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
bug ticket: https://github.com/ita-social-projects/StreetCode/issues/852
=> remove react helmet + add banner

src/features/ProgressBar/ProgressBar.component.tsx, src/features/ProgressBar/ProgressBarSection/ProgressBarSection.component.tsx, src/features/ProgressBar/ProgressBarSection/ProgressBarSection.styles.scss
=> Fixed progress bar visibility and popups

src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFirst/SectionFirst.component.tsx, src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFourth/SectionFourth.component.tsx, src/features/AdditionalPages/PrivatePolicyPage/Title/Title.component.tsx
Reverts ita-social-projects/StreetCode_Client#1026
Fix #847
=> Fix issue 847 Fix Url Ref

src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.styles.scss, src/assets/sass/variables/_variables.colors.scss, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
=> Fixed the amount buttons and input in donates modal

src/app/stores/source-category-store-create.ts, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Fix for fans category editing

package.json, src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/app/common/components/modals/Partners/PartnersModal.styles.scss, src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
=> Fixed Issue 870, 871

src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.styles.scss
dev
##Description
Set fixed position for arrows in connection(streetcode) and took away arrows` animation 
ToDo
ToDo
ToDo
=> set fixed position for arrows in connection(streetcode)

jest.config.ts, package-lock.json, package.json, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
* **Example of imports:** import JobsModal from '@/features/AdminPage/JobsPage/JobsModal/JobsModal.component';
**_In addition, Jest Code Coverage Report has been added_**
Explanation of columns:
- **Stmts (Statements)**: shows statement coverage
- **Branch**: indicates if each branch (also called DD-path) of each condition structure (such as in if and switch statements) been executed. For example, checks if both the true and false branches in the if statement have been executed.
- **Funcs (Functions)**: indicates if each function (or subroutine) in the program has been called
- **Lines**: indicates if each executable line in the source file has been executed
- **Uncovered Line #s (Uncovered Line Numbers)**: this is a list of line numbers that were not covered by the tests. If you see that …
=> Jest config

src/assets/sass/mixins/_utils.mixins.scss, src/features/AdminPage/AdminPage.styles.scss, src/features/AdminPage/ForFansPage/ForFansPage/CategoryAdminModal.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx, src/features/AdminPage/PageBar/PageBar.styles.scss, src/features/AdminPage/PartnersPage/Partners.component.tsx, src/features/AdminPage/PartnersPage/Partners.styles.scss, src/features/AdminPage/StreetcodesTable/SearchMenu.styles.scss, src/features/AdminPage/TeamPage/TeamPage.component.tsx, src/features/AdminPage/TeamPage/TeamPage.styles.scss, src/index.scss
Made admin-page prettier (buttons, paddings) and refactor css classes to reduce duplication
https://github.com/ita-social-projects/StreetCode_Client/assets/91199925/374ebc6d-19b5-445e-acc1-64776ea5017c
=> adjust admin page styles

src/app/stores/partners-store.ts, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx, src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.styles.scss, src/features/AdminPage/PartnersPage/PartnerModal/constants/socialOptions.ts
No ticket, just test if everything work (create & update of partner on admin page)
=> Refactor partner modal

src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
[StreetCode page] Title of the description isn't centered with text #604
Change padding from 10 px to 0 in the main text field
=> Issue 604 (Change padding in main text field)

src/app/common/components/TagList/TagList.component.tsx, src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx, src/app/common/components/modals/Tags/TagsModal.component.tsx, src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx, src/app/stores/tags-store.ts, src/features/StreetcodePage/MainBlock/MainBlock.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx, src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx
=> fix related events modal

src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
Refactor code styles and reduce code amount and complexity
=> - refactor code (no business logic changes)

src/features/AdditionalPages/NotFoundPage/NotFound.styles.scss
Removed extra padding on mobile and add @media only for better browser support
tiket: https://github.com/ita-social-projects/StreetCode/issues/775
=> try to fix problem on 404 page with old browsers on iphone

src/features/AdditionalPages/NotFoundPage/NotFound.styles.scss
tiket: https://github.com/ita-social-projects/StreetCode/issues/775
=> - refactor to mobile-first

src/features/AboutUsPage/TeamMembers/TeamPositionsSlider/TeamPostionSlider.component.tsx
The headlines in the 'Tabs' section don't match those in the mockup #764
Change amount of pictures for different sizes of screen
=> Change amount of pictures for different size of screen

src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
- Open main page
- Scroll down to Instagram block
- Click on "Зацінити інстаграм" button
The Instagram page should open in a new tab
=> - refactor to open in a new tab

src/app/common/components/modals/DeleteStreetcode/DeleteStreetcodeModal.component.tsx, src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/app/common/components/modals/HeaderLogin/HeaderLoginModal.component.tsx, src/app/common/components/modals/InterestingFacts/InterestingFactsModal.component.tsx, src/app/common/components/modals/MapStatisticsModal/StatisticsModal.component.tsx, src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx, src/app/common/components/modals/Sources/SourcesModal.component.tsx, src/app/common/components/modals/Survey/SurveyModal.component.tsx, src/app/common/components/modals/Tags/TagsModal.component.tsx, src/app/common/components/modals/Terms/DeleteTerm/DeleteTermModal.component.tsx, src/app/common/components/modals/Terms/EditTerm/EditTermModal.component.tsx, src/app/layout/ModalWrapper.component.tsx, src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.component.tsx, src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.component.tsx
=> fix modals closing

src/app/api/news/news.api.ts, src/app/api/streetcode/streetcodes.api.ts
Try to edit and delete news and streetcode. It should return 200 status code
=> Remove agent frontend

src/app/common/components/Editor/EditorUtilities/quillUtils.utility.ts, src/app/common/components/Editor/QEditor.component.tsx, src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx, src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
=> 1097 rq text editor fix validation of texts for the max allowable length

src/app/api/news/news.api.ts, src/app/api/streetcode/streetcodes.api.ts, src/app/common/components/modals/Donates/DonatesModal.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
=> try to fix donate button

__mocks__/@stores/root-store.tsx, src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.spec.tsx
Little attemt to fix some of the mocks for unit test `TeamModal.component.spec.tsx`
=> Unit tests for team adminpage with fx

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss
BEFORE:
AFTER:
How to test: check UI for horizontal paddings on streetcode create/update
=> fix layout on streetcode edit/create

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
How to test:
1. Add AR link to streetcode in admin-panel
2. Check if button "Оживити картинку" is **absent** on streetcode page (StreetcodeCard component) on all variations of screen width
=> Remove button on streetcode page

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> update main streetcode card

src/app/common/components/CardText/CardText.component.tsx, src/app/common/components/modals/Sources/SourcesModal.styles.scss, src/app/common/utils/window.utility.tsx, src/assets/sass/mixins/_utils.mixins.scss, src/features/AboutUsPage/Vacancies/Vacancy/Vacancy.syles.scss, src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.component.tsx, src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.styles.scss, src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx, src/features/AdditionalPages/NewsPage/News.component.tsx, src/features/AdditionalPages/NewsPage/News.styles.scss, src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFifth/SectionFifth.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx, src/features/AdminPage/NewStreetcode/MainNewStreetcode.styles.scss, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx, src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss, src/features/StreetcodePage/Streetcode.component.tsx, src/features/StreetcodePage/TextBlock/ReadMore/ReadMore.styles.scss
=> Two-line title for interesting facts

src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.component.tsx
=> Update text in AR block

src/app/api/agent.api.ts, src/index.tsx
How to check:
1. Run project and check if everything was fetched successfully (on any page)
2. Open agent.api.ts file, and you should not see any typescript or linter errors
3. If you start typing window._env_... the IDE should show you hints that _env_ variable have 3 properties that was declared in src/index.tsx file
=> declare global window type

src/app/common/components/modals/Sources/SourcesModal.styles.scss, src/app/common/utils/removeHtmlTags.utility.ts, src/features/AdditionalPages/NewsPage/News.styles.scss
dev
* The attribute dir set to "ltr" is a distinctive feature of the old editor TinyMCE, by which we can recognize the text that has been created with its help.
* You can use these texts for testing: https://docs.google.com/document/d/1grhYE0C2u5_UhSI6_JsfSda_IdyHS95bkfIkUt8PJ5E/edit?usp=sharing
* **Please check expected result in the second ticket**
ToDo
ToDo
ToDo
=> 1080 editor difference in blocks fans news

src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss
[Streetcode][Wow-факти] The main text of the 'Wow-факти' card goes beyond the card #897
ToDo
Change style css
=> Fix wow-facts modal

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
=> fix streetcode card

package-lock.json, package.json, public/index.html, yarn.lock
dev
* Removed all TinyMCE packages as it is already replaced with another editor completely
ToDo
ToDo
ToDo
=> Removed TinyMCE cdn & packages

src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/app/common/constants/error-messages.constants.ts
How to review:
1. Go, for example, to the page 'Контакти'.
2. Fill in the input fields.
3. Do not check the recaptcha.
4. Click on the button 'Відправити'
Result:
A message should appear.
**Note!** If you check the recaptcha and send an email, ignore the message: 
This is because sending emails does not work locally.
=> made recaptcha required

package-lock.json, package.json, src/features/StreetcodePage/DonateBtn/DonateBtn.component.tsx, src/features/StreetcodePage/Streetcode.component.tsx, yarn.lock
Fixed bug with displaying Survey modal by changing the logic from scroll to TickerBlock tracking.
=> Fix bug #1178

public/index.html
Fixed bug with an automatic zoom-in on IOS.
Issue detailes: https://github.com/ita-social-projects/StreetCode/issues/964
=> Fix bug #964

src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/modals/Partners/PartnersModal.component.tsx
=> add a limit to the number of messages

src/features/MainPage/InstagramBlock/InstagramSliderItem/InstagramSliderItem.component.tsx
Summary of issue
to make it swipe on the computer and not go straight to the streetcodes
ToDo
to add handleMouse to see if we swipe or move to block
=> Fix bug instagram slider

src/app/common/components/CardText/CardText.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
Fixed issue #950 by removing "Трохи ще..." button and changing adaptation for wow-fact slider (added one more intermediate adaptation at 1325 px between 1200 and 1450 for more smooth change of slider).
=> Fix bug issue #950

src/app/common/components/modals/ConfirmationModal/ConfirmationModal.component.tsx
=> fixed issue-958

src/app/common/components/modals/InterestingFacts/InterestingFactsModal.styles.scss
=> Change width in modal window to 340px

src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
=> fixed validation

src/app/common/components/CardText/CardText.component.tsx
=> quick fix issue-1264

src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigures.component.tsx
dev
fix tags appearance on streetcode page when use screen >1024 and sencor screen
**Ticket [#969](https://github.com/ita-social-projects/StreetCode/issues/969)**
=> fix tags appearance on streetcode page when use screen >1024 and sencor screen

jest.config.ts
=> feat: reduce coverage theshold

src/features/StreetcodePage/QRBlock/QR.styles.scss, src/features/StreetcodePage/QRBlock/QRMobile/QRMobile.styles.scss
fixed positioning of AR block according to Figma mockup
=> fixed positioning of AR block

src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
=> Grammatical error fix (issue-943)

src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
dev
* [Main Github ticket](https://github.com/orgs/ita-social-projects/projects/21/views/1?pane=issue&itemId=56476782)
Close button doesn't work after failed submission
changed useState value to false in case of error during submission
=> close button now works after failed submission

src/app/common/components/FileUploader/FileUploader.component.tsx, src/models/media/image.model.ts
Merge at the same time with [backend part](https://github.com/ita-social-projects/StreetCode/pull/1356)
=> Add alt as empty string to every image we create

src/app/api/streetcode/streetcodes.api.ts, src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/StreetcodesTable/StreetcodesTable.component.tsx
There were no pagination for streetcodes in admin panel
Change property name from page to pages to parse json correctly
Checkout to the branch and open admin panel. Pagination should be presented
=> fix name of property

src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
[From Customer][Для звʼязків][Catalog] The "Для звʼязків" image isn't displayed on catalog
added a check if there is a picture related to the story, it is displayed, if not, it is blackandwhite image
=> fixed issue-966

src/features/MainPage/NewsSlider/NewsSlider.component.tsx
=> feat: make dots dissapear on 1025px not 1024px on NewsSlider on MainPage

package-lock.json, package.json, src/app/common/components/CardText/CardText.component.tsx, src/features/SlickSlider/InterestingFactSliderSlickSlider.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.component.tsx, yarn.lock
Fixed copy from wow-fact and chronology according to the requirements
=> fix copy from the wow-facts and chronology

src/app/api/agent.api.ts, src/app/common/services/auth-service/AuthService.ts
Handled token autorefreshment by using axios interceptor.
=> Handle token autorefreshment

src/features/AdminPage/NewStreetcode/StreetcodeArtsBlock/components/Download.component.tsx
There was no possibility to delete an art from the art gallery uploader
=> Fixed art delete

src/app/common/components/modals/Donates/DonatesModal.styles.scss, src/app/common/components/modals/Sources/SourcesModal.styles.scss, src/features/AdditionalPages/NewsPage/News.styles.scss, src/features/AdditionalPages/PrivatePolicyPage/PrivatePolicy.styles.scss, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx, src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss, src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss, src/features/StreetcodePage/TextBlock/TextBlock.styles.scss
=> Link color and underline fix

src/features/MainPage/TeamSlider/TeamItemSlider/TeamItemSlider.styles.scss
=> team page styles fix

src/app/api/agent.api.ts
=> fix refresh token

src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
There was an issue with social networks, as we were able to add more than one link to the same Social Network category. Fixed by addiding extra check for existence of Link with given social network.
=> Fixed social networks issue

src/app/common/components/ArtGallery/components/OneToFourAndFiveAndSixSlide/OneToFourAndFiveAndSixSlide.styles.scss, src/app/common/components/ArtGallery/components/OneToFourAndFiveToSixSlide/OneToFourAndFiveToSixSlide.styles.scss, src/app/common/components/ArtGallery/components/OneToFourSlide/OneToFourSlide.styles.scss, src/assets/sass/variables/_variables.sizes.scss
dev
* [Main Github ticket](https://github.com/orgs/ita-social-projects/projects/21/views/10?sliceBy%5Bvalue%5D=Shossy&pane=issue&itemId=62417354)
some art gallery slides didn't correspond to mockup
changed css styles
=> feat: fixed styles in art gallery

src/app/common/components/Draggable/Draggable.styles.scss, src/app/common/components/Draggable/Draggable.tsx
=> fixed preview dragging bug

src/app/stores/streetcode-art-slide-store.ts, src/app/stores/streetcode-current-store.ts
=> return previous store

src/app/common/components/ArtGallery/ArtGalleryBlock.component.tsx, src/app/stores/streetcode-art-slide-store.ts, src/app/stores/streetcode-current-store.ts
=> fix art gallery

src/app/common/components/modals/Partners/PartnersModal.component.tsx
dev
* [Main Github ticket](https://github.com/ita-social-projects/StreetCode/issues/1483)
Wrong error message is displayed after three requests to become partners are sent
Corrected if statement
=> feat: fixed error message

src/features/AdminPage/NewStreetcode/CategoriesBlock/CategoriesAdminModal/CategoriesAdminModal.component.tsx
=> remove alert

src/features/AdminPage/NewStreetcode/StreetcodeArtsBlock/components/Download.component.tsx, src/features/AdminPage/NewStreetcode/StreetcodeArtsBlock/components/DownloadStyles.styles.scss
=> Restrict uploading of wrong types

src/features/AdminPage/NewStreetcode/MainBlock/MainBlockAdmin.component.tsx
forbid user to input letters in number field
=> forbid user to input letters in number field

src/features/StreetcodePage/TimelineBlock/TimelineBlock.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSlider.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.component.tsx, src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiperEdgeBtn/TimelineSwiperEdgeBtn.styles.scss, src/features/StreetcodePage/TimelineBlock/Timespan/Timespan.component.tsx
=> add dots and crucial dates for <1024 viewport

src/app/common/components/ArtGallery/ArtGalleryBlock.component.tsx
=> fix empty gallery

Jenkinsfile
=> Update jenkinsfile for new branch

config/webpack.prod.js, public/index.html
Site isn`t available for old users
Disabled cache
=> fix: Add Cache-Control header to index.html

config/webpack.prod.js
=> Add networkFirst caching mode for js and css files

src/features/AdminPage/TagsPage/TagsPage/TagAdminModal.component.spec.tsx, src/features/AdminPage/TagsPage/TagsPage/TagAdminModal.style.scss, src/features/AdminPage/TagsPage/TagsPage/TagAdminModal.tsx
Ticket [#1598](https://github.com/ita-social-projects/StreetCode/issues/1598)
=> Message title fixed in tag modal on admin page

config/webpack.dev.js, config/webpack.prod.js, public/env-config.js, src/app/common/components/withClearCache.tsx, src/index.tsx
=> Add automatic cache cleaning after new build

src/app/common/components/withClearCache.tsx
=> fix check statement

src/features/StreetcodePage/SourcesBlock/Sources.styles.scss
fix styles for sources component
=> [Streetcode][Для фанатів] Cards are not left aligned

nginx/nginx.conf
=> add "no cache" header to nginx.conf

nginx/nginx.conf
=> fix nginx.conf

src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.styles.scss, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx, src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.styles.scss
Ticket [#1281](https://github.com/ita-social-projects/StreetCode/issues/1281)
=> Wow facts slider fixed for 3 slides and partially for 2 slides

src/app/common/components/ContactForm/ContactForm.component.tsx, src/app/common/components/modals/Partners/PartnersModal.component.tsx, src/models/email/email.model.ts
* Ticket ita-social-projects/StreetCode#976
* [backend part](https://github.com/ita-social-projects/StreetCode/pull/1696)
Add note to email, where did it come from Contacts page or Partners Page
- Source property added to Email entity
- Source added while sending emails from Contacts page or Partners page
=> Source added to Email message

src/features/AdminPage/CategoriesPage/CategoriesPage.component.tsx, src/features/AdminPage/ContextPage/ContextMainPage.component.tsx, src/features/AdminPage/JobsPage/JobsTable/JobsTable.component.tsx, src/features/AdminPage/NewsPage/News.component.tsx, src/features/AdminPage/PartnersPage/Partners.component.tsx, src/features/AdminPage/TagsPage/TagsMainPage.component.tsx, src/features/AdminPage/TeamPage/TeamPage.component.tsx, src/features/AdminPage/TeamPositionsPage/TeamPositionsMainPage.component.tsx
- [Main GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1706)
- After fixing Merge Conflicts in the previous PR, the loading indication on some pages broke.
- Now the loading indication works fine.
=> Fixed disappeared loading indication in some pages

public/index.html, public/robots.txt
* [GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1841)
Our website is accessible from google
robots.txt was changed and meta "noindex" was added.
=> Prevent site from appearing in the search results

src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx, src/features/StreetcodePage/PdfDocument/StreetcodeDocument.component.spec.tsx, src/features/StreetcodePage/PdfDocument/StreetcodeDocument.component.tsx
dev
* [GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1835)
1. Fixed error that appears when creating pdf for streetcode that does not contain facts
2. Hide all section headings if they have no content
3. If streetcode doesnt have colored image, white-black image is used instead
=> Fix bugs on Streetcode document

src/features/AdditionalPages/NewsPage/News.component.tsx
* [Github ticket](https://github.com/ita-social-projects/StreetCode/issues/1933)
Extra bracket on the page due to missing curly braces in the code.
Fixed conditional rendering in the NewsPage component.
=> Fix conditional rendering in NewsPage component.

src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.styles.scss
* [Github ticket](https://github.com/ita-social-projects/StreetCode/issues/2042)
Requirements were changed: "A single Streetcode card contains on the desktop image, “Назва стріткоду”, “Короткий опис”, “Тизер”, and the button "До стріткоду". Table/mobile: image, “Назва стріткоду” and the button "До стріткоду"."
Table/mobile: changed from subtitle to title of the streetcode
=> Feature/ issue 2042
