ita-social-projects/StreetCode_Client

- src/app/common/components/modals/Tags/TagsSliderModal/TagsSliderModal.component.tsx
- src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
- src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.styles.scss
Added max-height and overflow props to related tag list class, so it would not display tags below the second row
> Fix RF cards' tags

- src/app/stores/streetcodes-bytag-store.ts
dev
https://github.com/ita-social-projects/StreetCode_Client/issues/391
The modal tag not includes images of related figure cards and includes the text of the tags.
Included in figures modal image by calling the ImageAPI and removed tags' text.
> Fix RF tag modal.

- src/features/AdminPage/NewStreetcode/TimelineBlock/NewTimelineModal/NewTimelineModal.component.tsx
> 401 adminchronology block when the admin add more than 50 characters to the context field all text is erased

- .env
- Dockerfile
- docker-compose.yml
- env.sh
- public/index.html
- src/app/api/agent.api.ts
dev
Now we can configure API_URL link at docker compose runtime as an environmental variable. Do not use latest images from saymolet/streetcode*:latest. They are configured with stage link and https. In near future stage and production environments will only have one or the other: dns+https or just plain IP address as access points. 
Street Code Docker Hub repo will host all future images. 
ToDo
ToDo
ToDo
> configure backend link as env variable at runtime

- src/features/StreetcodePage/MainBlock/BreadCrumb/BreadCrumb.styles.scss
The "СТРІТКОДИ" is not supposed to be highlighted when mouse hovers:
ToDo
ToDo
ToDo
> Streetcode link higlighting

- src/app/common/components/ScrollToTopBtn/ScrollToTopBtn.styles.scss
- src/app/common/components/modals/Donates/DonatesModal.styles.scss
- src/app/common/components/modals/HeaderLogin/HeaderLoginModal.styles.scss
- src/app/common/components/modals/ListenText/ListenText.styles.scss
- src/app/common/components/modals/Partners/PartnersModal.styles.scss
- src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.styles.scss
- src/app/common/components/modals/Survey/SurveyModal.styles.scss
- src/assets/sass/variables/_variables.colors.scss
- src/features/AdditionalPages/ContactUsPage/ContactUs.styles.scss
- src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.styles.scss
- src/features/AdditionalPages/NewsPage/News.styles.scss
- src/features/AdditionalPages/PartnersPage/ModalButtons/PartnersBtnCircle/PartnersBtnCircle.styles.scss
- src/features/AdditionalPages/SupportUsPage/components/DonationBlock.styles.scss
- src/features/AdminPage/NewStreetcode/MapBlock/StatisticsStreetcodeAdmin/StatisticsAdmin.styles.scss
- src/features/MainPage/StaticBanners/StaticBanner.styles.scss
- src/features/StreetcodePage/DonateBtn/DonateBtn.styles.scss
- src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
Box shadows not working properly in Safari
- change all filter:drop-shadow to box-shadow (where it's possible)
- add transform3d(0;0;0;) to all filter:drop-shadow that was left to display them right in Safari
- format styling with linter in files that was changed (side effect of opening files with linter)
-
> Fix shadows

- src/app/layout/app/App.component.tsx
- src/app/layout/app/slick-slider.overrides.scss
- src/features/MainPage/TeamSlider/TeamComponent.styles.scss
- src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryBlock.styles.scss
- src/features/StreetcodePage/TimelineBlock/TimelineSwiper/TimelineSwiper.styles.scss
- fix all sliders (slick && swiper) not showing all dots on overflow
- fix dots get under "побачити всю команду" button
Steps to reproduce:
- visit page of any streetcode person 
- screen smaller to make part of dots overflow screen
Actual behaviour: 
- not all dots are showing on a screen
Expected behaviour:
- dots just jump to another row, so all dots are available to click
> - fix all sliders (slick && swiper) not showing all dots on overflow

- src/features/StreetcodePage/InterestingFactsBlock/InterestingFactItem/InterestingFactItem.component.tsx
- src/features/StreetcodePage/InterestingFactsBlock/InterestingFacts.component.tsx
dev
* The description of the image should be visible only for the central fact (when there are >= 3 of them)
ToDo
ToDo
ToDo
> Fixed wow-facts img description displaying

- src/app/layout/header/HeaderDrawer/HeaderDrawer.component.tsx
dev
* When a specific streetcode page is opened, the burger menu shows "Головна" as the current section. "Стріткоди" section must be shown.
ToDo
ToDo
ToDo
> Minor change of burger menu logic

- src/app/common/components/modals/Sources/SourcesModal.styles.scss
- src/features/AdditionalPages/NewsPage/News.styles.scss
On "news" and "for fans" there is no numbering in the text, although it is present in the editor.
ToDo
ToDo
ToDo
> Fixed numering for ol ul

- src/app/stores/streetcodes-catalog-store.ts
- src/features/StreetcodeCatalogPage/StreetcodeCatalog.component.tsx
dev
ToDo
issue [Change "sunshine" animation while loading in streetcode catalogs#745](https://github.com/ita-social-projects/StreetCode_Client/issues/745)
ToDo
ToDo
> Change loading sunshine icon in catalog 

- src/features/AdditionalPages/NewsPage/News.component.tsx
- src/features/AdditionalPages/NewsPage/News.styles.scss
- src/features/AdditionalPages/NewsPage/RandomNewsBlock.component.tsx
On the news page:
1) For MVP, we always make the picture on the right
2) Add the date under the heading
Also fixed a lot of code and moved the component to another file
> Image moved to right for wide screens and date added by Mariia Padalka

- src/features/MainPage/TopCarousel/TopCarousel.styles.scss
Issue #767 
The aspect ratio of the banner image is changed in proportion to the change in screen width. - see. design in fig [[mocup.](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?node-id=4762%3A8707&mode=dev)]
ToDo
> Incorrect aspect ratio at 1200 screen size

- src/features/AdminPage/NewStreetcode/TextBlock/TextForm/Editors/TextEditor.component.tsx
> add changing element with useRef

- src/features/StreetcodePage/Streetcode.component.tsx
- src/features/StreetcodePage/Streetcode.styles.scss
- Try to open streetcode with different screen sizes and slow internet speed (you can limit it in DevTools)
Loader should not be squeezed or stretched and while animation is running you should not be able to scroll
> fix loader and remove scrollbar when loading

- .env
- docker-compose.yml
- public/index.html
> Front env variable

- src/features/AboutUsPage/TeamMemberCard/TeamMemberCard.styles.scss
> if name of team member is long, it should be displayed in 2 lines

- src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss
- src/features/AdminPage/NewStreetcode/ArtGallery/components/ArtGallery/ArtGalleryAdminStyles.styles.scss
- src/features/StreetcodePage/ArtGalleryBlock/ArtGalleryItem/ArtGallerySlideItem.styles.scss
When hover on art gallery item (no matter big or small, no matter what screen) there should not be any text overflow. Also, when you open art to full screen you should see all text without '...'
> fix overflow in cards and lightbox mobile

- src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.styles.scss
> fix news button overflowing

- src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
- src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansBlock.component.tsx
- src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
> Fixed loading of fans modal categories

- src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
dev
fix fetching streetcode on streetcode page, when resolution is too big or page is too scaled
Before:
After:
ToDo
ToDo
ToDo
> fix not fetching streetcode on streetcode catalog page

- src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
As a user I want to click on streetcode slider card ( button "До стріткоду ") on main page and if it has no text on it I should not be redirected
> handle click when streetcode url isn't loaded

- src/app/stores/news-store.ts
- src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
> fix news modal from closing when image is not created (#1061)

- src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
As a user I don't want to wait for a long time to check if news url is unique when I submit news modal
> Remove get all on news modal submit

- src/features/AdditionalPages/NewsPage/News.styles.scss
As a user, I want to see the news page in safari browser the same way I see it in Google Chrome
> Fix news image on safari

- src/features/MainPage/Heading/Heading.styles.scss
dev
Our partners title takes only 1 row, instead of two(width<360px)
Before:
Afrer:
ToDo
ToDo
ToDo
> fix our partners title

- config/webpack.dev.js
- config/webpack.prod.js
This PR aims to fix code build for app deployment
Main chages:
1) Revert resolved path for dist folder for dev and prod set ups
More detailed description:
Apparently one of the steps of code build is to check and form checksum of dist folder
`COPY --from=build /app/dist /usr/share/nginx/html`
But when codebuild does not find dist folder in certain place it thoughts an error
`ERROR: failed to calculate checksum of ref 54db9db1-1221-47af-b500-b94711656e2d::oegkooqz1emghikpa5t89zje6: "/app/dist": not found`
Why codebuild can not find dist folder?
Apperanty with this [PR](https://github.com/ita-social-projects/StreetCode_Client/pull/1041) there was a change that dist folder will be placed in diff location `[__dirname]/dist` (as official documentation …
> Fix code build for app deployment

- src/app/common/components/Editor/QEditor.component.tsx
- src/app/common/components/modals/Sources/SourcesModal.styles.scss
- src/app/common/utils/removeHtmlTags.utility.ts
- src/features/AdditionalPages/NewsPage/News.styles.scss
- src/features/AdminPage/JobsPage/JobsModal/JobsModal.component.tsx
- src/features/AdminPage/NewStreetcode/ForFansBlock/ForFansAdminModal/ForFansAdminModal.component.tsx
- src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
dev
**1. It's OK that you cannot save streetcode in this PR!**
**2. The bug with too big indentations in for fans modal window will be fixed as soon as higher priority tasks are completed**
ToDo
ToDo
ToDo
> Fixed indents in news page

- src/app/common/components/CardText/CardText.component.tsx
- src/app/common/utils/window.utility.tsx
- src/features/AdditionalPages/NewsPage/News.component.tsx
- src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
- src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
- src/features/StreetcodePage/Streetcode.component.tsx
Open streetcode and news from main page to test new redirect.
+ You should be able to right-click on the link and open it in a new tab
Also please check visuals on `StreetcodeSliderItem` (main page), `NewsSliderItem` (main page), `InterestingFactItem` (streetcode page), `VacancyComponent` (about us page) for **visual similarity** to prod or stage.
> refactor StreetcodeSliderItem and NewsSliderItem to use Link for redirects

- src/features/AboutUsPage/Vacancies/Vacancy/VacancyModal/VacancyModal.component.tsx
- src/features/AdditionalPages/ContactUsPage/MainBlock/ContactBlock/ContactBlock.component.tsx
- src/features/AdditionalPages/PrivatePolicyPage/SubSections/SubSectionFifth/SectionFifth.component.tsx
dev
**Links which should open in new tab:**
1. Vacancy modal - "Відгукнутись" button
2. "Контакти" page - clickable icon next to the streetcode gmail which leads to gmail new letter
3. "Політика конфіденційності" page - streetcode gmail which leads to gmail new letter
ToDo
ToDo
ToDo
> Links open in new tabs

- src/features/MainPage/NewsSlider/NewsSlider.component.tsx
- src/features/MainPage/NewsSlider/NewsSliderItem/NewsSliderItem.component.tsx
- src/features/MainPage/StreetcodeSlider/StreetcodeSliderItem/StreetcodeSliderItem.component.tsx
Please check the ability to "go back" from streetcode and news page when you open them from main page (with help of streetcodeSliderItem and newsSliderItem).
> Fix news and street code redirect

- src/features/AdminPage/PartnersPage/Partners.styles.scss
Open admin panel and check if the last tab in news tab is like on the screenshot below: 
The image doesn't overflow the table as on stage env
> Fix layout bug

- src/app/api/streetcode/streetcodes.api.ts
- src/app/stores/streetcode-mainpage-store.ts
- src/features/MainPage/StreetcodeSlider/StreetcodeSlider.component.tsx
Please check if no logic on admin panel isn't broken (Create, Delete, Update - on Streetcodes)
Also, if you visit main page and then go to some of the streetcodes (or any other subpage) and then click 'go back' browser arrow you should see streetcode slider with the data right away
> add caching to streetcode-slider

- src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
- src/features/SlickSlider/SlickSlider.styles.scss
Summary of issue
There isn't ability to swipe through the Instagram cards on the a tablet
Summary of change
remove a line swipe:windowSize.width<1025 from sliderProps
edit opacity in .slick-arrow to make more saturated arrows in instagram slide
> Fix bug swipe through instagram

- src/app/common/components/modals/Lightbox/LightboxComponent.styles.scss
- src/assets/sass/variables/_variables.colors.scss
dev
* [Main Github ticket](https://github.com/orgs/ita-social-projects/projects/21/views/10?sliceBy%5Bvalue%5D=Shossy&pane=issue&itemId=61100382)
Arrows are invisible on ArtGallery fullscreen size
Changed colors of arrows according to production version
> feat: fixed colors on arrows on ArtGallery full-screen view

- src/features/MainPage/InstagramBlock/InstagramBlock.component.tsx
Changed slider props to the same, as in team slider, so that it will be easier to swipe.
> Instagram slider required extra efford to swipe

- src/app/common/components/ArtGallery/components/BaseArtGallerySlide.styles.scss
Found out that the reason for dots under the title in art gallery is unset line height.
> Fixed line height to get rid of dots

- src/app/api/media/streetcode-art.api.ts
- src/app/common/components/ArtGallery/ArtGalleryBlock.component.tsx
- src/app/common/components/ArtGallery/constants/allSlidesTemplates.ts
- src/app/common/constants/api-routes.constants.ts
- src/app/stores/streetcode-art-slide-store.ts
Let me elaborate:
1. Get number of slides for specific streetcode
2. Fill streetcodeArtSlides with empty slides so the slick slider shows right number of dots
3. Then fetch ArtSlides as intended, 1 slide at a time, to reduce load time of ArtGallery
4. Swap default slide (fully white slide) with fetched slide
5. Done
> slick slider dots problem resolved

- jest.config.ts
- src/app/common/components/AudioPlayer/AudioPlayer.component.tsx
- src/app/common/components/ProtectedComponent.component.tsx
- src/app/common/components/modals/Donates/DonatesModal.component.tsx
- src/app/common/components/modals/ListenText/ListenText.component.tsx
- src/app/common/components/modals/ListenText/ListenText.styles.scss
- src/app/common/components/modals/RelatedFigures/RelatedFigureItemModal.component.tsx
- src/app/layout/app/App.component.tsx
- src/app/layout/footer/Footer.component.tsx
- src/app/layout/header/HeaderBlock.component.tsx
- src/app/layout/header/SearchBlock/SearchBlock.component.tsx
- src/app/layout/header/SearchBlock/SearchResultItem/SearchItem.component.tsx
- src/app/stores/subtitles-store.ts
- src/features/AdditionalPages/SupportUsPage/components/DonationBlock.component.tsx
- src/features/AdminPage/PartnersPage/PartnerLink.component.spec.tsx
- src/features/AdminPage/PartnersPage/PartnerLink.component.tsx
- src/features/MainPage/MainPage.component.tsx
- src/features/MainPage/NewsSlider/NewsSlider.component.tsx
- src/features/MainPage/TeamSlider/TeamComponent.component.tsx
- src/features/StreetcodeCatalogPage/StreetcodeCatalogItem/StreetcodeCatalogItem.component.tsx
- src/features/StreetcodePage/MainBlock/MainBlock.component.tsx
- src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.component.tsx
- src/features/StreetcodePage/RelatedFiguresBlock/RelatedFigureItem/RelatedFigureItem.component.tsx
- src/features/StreetcodePage/Streetcode.component.tsx
1. Fixed audio modal hides while navigating the site
2. Fixed site reloading while navigating some pages
3. Fixed double click on close audio modal not actually closing
4. Fixed random blink when audio modal ends closing
5. Fixed search block not hiding and clearing when clicked on search item
Ticket: [#1286](https://github.com/ita-social-projects/StreetCode/issues/1286)
> Audio keeps playing while navigating the site

- src/features/StreetcodePage/MainBlock/StreetcodeCard/StreetcodeCard.styles.scss
* Ticket ita-social-projects/StreetCode#904
The 'Прослухати текст'/'Аудіо на підході' button is cut off at the bottom right
Card rounding on Streetcode page removed on width 1024 and lower
> Card rounding on Streetcode page removed on width 1024 and lower

- src/features/AdminPage/PageBar/PageBar.component.tsx
- src/features/AdminPage/PageBar/PageBar.styles.scss
* Ticket ita-social-projects/StreetCode#1707
When a user uses the admin page, he may get confused in which section he is currently in ("Стріткоди", "Партнери", "Едітор", etc.), which makes it (admin page) difficult to use. The section user is on is not highlighted in any way.
Highlighting added to menu on admin panel
> Nav menu on admin panel now highlights the current section

- src/features/AboutUsPage/TeamMembers/TeamMembers.component.scss
* Ticket ita-social-projects/StreetCode#891
Team members slider is highlighted blue when tapped
Team members slider is not highlighted when tapped
> Team members slider is highlighted when tapped

- src/features/StreetcodePage/PartnersBlock/Partners.component.tsx
- src/features/StreetcodePage/PartnersBlock/Partners.styles.scss
Ticket [#1650](https://github.com/orgs/ita-social-projects/projects/21/views/1?pane=issue&itemId=74376032)
> Streetcode page bottom space fixed when partners is absent

- src/features/AdminPage/CategoriesPage/CategoriesPage.component.tsx
* Ticket ita-social-projects/StreetCode#947
There are many identical API requests for images.
Prevented images from loading repeatedly.
>  Prevented images from loading repeatedly.

- src/app/common/components/modals/validators/imageValidator.tsx
- src/app/common/constants/file-types.constants.ts
- src/features/AdminPage/CategoriesPage/CategoriesPage/CategoryAdminModal.component.tsx
- src/features/AdminPage/CategoriesPage/CategoriesPage/CategoryAdminModal.styles.scss
- src/features/AdminPage/NewStreetcode/InterestingFactsBlock/FactsAdminModal/InterestingFactsAdminModal.component.tsx
- src/features/AdminPage/NewStreetcode/MainBlock/FileInputsPart.component.tsx
- src/features/AdminPage/NewStreetcode/StreetcodeArtsBlock/components/Download.component.tsx
- src/features/AdminPage/PartnersPage/PartnerModal/PartnerModal.component.tsx
- src/features/AdminPage/TeamPage/TeamModal/TeamModal.component.tsx
* Ticket ita-social-projects/StreetCode#1724
When attempting to upload a non-accepted photo format (e.g., a "pdf" file) to the "Картинка" field, the system does not display an error message.
The "Зберегти" button remains activated, allowing the user to proceed despite the invalid file format.
When attempting to upload a non-accepted photo format error message appears and "Зберегти" button becomes disabled where needed
> Image validation added for most modals where needed

- src/features/AdminPage/Login/AdminLogin.component.tsx
- src/features/AdminPage/Login/AdminLogin.style.scss
* Ticket ita-social-projects/StreetCode#1443
Under the 'Логін' field, the 'Пароль' field is shifted to the right.
- The 'Пароль' field is located exactly below the 'Логін' field.
- Captcha centered and bottom margin added
- Login button centered
> Admin login page made a little bit prettier

- src/app/stores/partners-store.ts
- src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
- src/features/AdminPage/NewStreetcode/PartnerBlock/PartnerBlockAdmin.components.tsx
* Ticket ita-social-projects/StreetCode#1777
We have 2 partners that set all Streetcodes by default, these are “Український інститут національної пам'яті” and “Railsware”. When we go to the admin page and edit any Streetcode, we don’t have partner labels by default in the “Партнери” section, which can confuse the user of the admin page.
Moreover, in the drop-down list of the same section they are not marked as selected.
Partners that are visible everywhere disabled in partners list while editing streetcode
> Partners that are visible everywhere disabled in partners list while editing streetcode

- src/features/AdminPage/NewStreetcode/MainNewStreetcode.component.tsx
- src/features/AdminPage/NewStreetcode/TextBlock/TextBlock.component.tsx
- src/features/AdminPage/NewStreetcode/TextBlock/TextForm/TextForm.component.tsx
- [Main GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/1780)
- 'Заголовок' text disappears when admin edits Streetcode.
- The 'Заголовок' field was not set properly in the code and it was decided to set it by passing the form and calling a special method.
> Solved problem with disappeared 'Заголовок' field in Streetcode edit mode

- src/features/StreetcodePage/TimelineBlock/TimelineBlock.styles.scss
- src/features/StreetcodePage/TimelineBlock/TimelineItem/TimelineItem.styles.scss
- [Main GitHub ticket](https://github.com/ita-social-projects/StreetCode/issues/861)
- The text of the card spills over into the white frame.
- Now the text no longer overlaps the frame.
> Fixed an issue with text overlapping the frame in the timeline

- src/features/AdminPage/CategoriesPage/CategoriesPage/CategoryAdminModal.component.spec.tsx
- src/features/AdminPage/CategoriesPage/CategoriesPage/CategoryAdminModal.component.tsx
- src/features/AdminPage/NewsPage/NewsModal/NewsModal.component.tsx
- yarn.lock
The main issue involves adding validation to ensure that News entities have unique titles within the system. The current implementation lacks a check, which allows duplicate news entries with the same title, leading to potential conflicts and confusion when managing content.
- Implemented a validation check that prevents duplicate titles when creating or updating a News entity.
- Modified the form to validate title uniqueness before submission.
- Adjusted the error handling logic to notify the user if a duplicate title is detected.
> Added unique title validation for News entities

- src/app/stores/streetcode-page-loader-store/streetcode-page-loader-store.spec.ts
- src/app/stores/streetcode-page-loader-store/streetcode-page-loader-store.ts
- src/features/StreetcodePage/Streetcode.component.tsx
- src/index.scss
* [Github ticket](https://github.com/ita-social-projects/StreetCode/issues/2018)
* [Previous PR related to this issue](https://github.com/ita-social-projects/StreetCode_Client/pull/1508)
Every page of site loads from the bottom of the pageToDo
Smooth scrolling was disabled
> remove smooth scrolling when switching to another page
